{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatbot.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      name: redis
  selector:
    app.kubernetes.io/component: redis
    {{- include "chatbot.selectorLabels" . | nindent 4 }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chatbot.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: redis
    {{- include "chatbot.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
      {{- include "chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
        {{- include "chatbot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "redis/redis-stack-server:7.2.0-v17"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}  
          ports:
            - containerPort: {{ .Values.redis.port }}
          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - name: redis-data
              mountPath: {{ .Values.redis.persistence.mountPath }}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}    
{{- end }}
