apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "persona-ai-creator.fullname" . }}-config
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  KUBECONFIG_PATH: "/app/secrets/team-g-kubeconfig.yaml"
