apiVersion: v1
kind: Secret
metadata:
  name: {{ include "persona-ai-creator.fullname" . }}-secret
type: Opaque
stringData:
  JWT_SECRET: {{ required "appSecrets.jwtSecret is required" .Values.appSecrets.jwtSecret | quote }}
  SHARED_POSTGRES_PASSWORD: {{ required "appSecrets.sharedPostgresPassword is required" .Values.appSecrets.sharedPostgresPassword | quote }}
  team-g-kubeconfig.yaml: |
{{ required "appSecrets.kubeconfig is required" .Values.appSecrets.kubeconfig | indent 4 }}
