apiVersion: v1
kind: Secret
metadata:
  name: {{ include "persona-ai-creator.fullname" . }}-secret
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.appSecrets.jwtSecret | quote }}
  SHARED_POSTGRES_PASSWORD: {{ .Values.appSecrets.sharedPostgresPassword | quote }}
  team-g-kubeconfig.yaml: |
{{ .Values.appSecrets.kubeconfig | indent 4 }}
