apiVersion: v2
appVersion: 1.3.2
dependencies:
- condition: vs-agent-chart.enabled
  name: vs-agent-chart
  repository: oci://registry-1.docker.io/veranalabs
  version: v1.9.2
description: Helm chart to deploy Hologram Generic AI Agent Verifiable Service
name: hologram-generic-ai-agent-chart
version: v1.11.2
